services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: campimove_backend
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=campimove_api
      - DB_USER=postgres
      - DB_PASS=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: campimove_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080"

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=campimove_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  pgdata: